wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701677726.239041
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.35.2
      8:
      - 5
      - 9
      13: linux-x86_64
