model_name: "openai/whisper-large-v3"
class_num: 8
data_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech"
batch_size: 8
num_workers: 8
epochs: 10
lr: 0.0001
weight_decay: 0.00001
save_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech/weights"
log_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech/logs"
log_interval: 200
