model_name: "openai/whisper-base"
class_num: 8
data_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech"
batch_size: 4
num_workers: 12
epochs: 100
lr: 0.0001
weight_decay: 0.000001
save_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech/weights"
log_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech/logs"
log_interval: 20