model_name: "openai/whisper-large-v3"
class_num: 8
data_path: "/data_3/teddy_research/dataset/speech_emotion"
batch_size: 8
num_workers: 4
epochs: 20
lr: 0.000025
weight_decay: 0.0000001
save_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech/weights"
log_path: "/home/ec2-user/teddy_workspace/data/speech_emotion/Speech/logs"
log_interval: 5